version: '3.8'

services:
  db:
    hostname: db
    image: pgvector/pgvector:pg16
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
      
volumes:
  db_data: